In [ ]:
# numpy doc https://numpy.org/doc/stable/user/quickstart.html

In [1]:
import numpy as np

In [12]:
np.ScalarType

(int,
 float,
 complex,
 bool,
 bytes,
 str,
 memoryview,
 numpy.bool_,
 numpy.complex64,
 numpy.clongdouble,
 numpy.complex128,
 numpy.float16,
 numpy.float32,
 numpy.longdouble,
 numpy.float64,
 numpy.int8,
 numpy.int16,
 numpy.int32,
 numpy.intc,
 numpy.int64,
 numpy.timedelta64,
 numpy.datetime64,
 numpy.object_,
 numpy.bytes_,
 numpy.str_,
 numpy.uint8,
 numpy.uint16,
 numpy.uintc,
 numpy.uint32,
 numpy.uint64,
 numpy.void)

In [13]:
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64],
 'complex': [numpy.complex64, numpy.complex128],
 'others': [bool, object, bytes, str, numpy.void]}

In [14]:
np.sctypeDict

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.intc,
 5: numpy.intc,
 'uint': numpy.uint32,
 'I': numpy.uintc,
 6: numpy.uintc,
 'intp': numpy.int64,
 'p': numpy.int64,
 9: numpy.int64,
 'uintp': numpy.uint64,
 'P': numpy.uint64,
 10: numpy.uint64,
 'long': numpy.int32,
 'l': numpy.int32,
 7: numpy.int32,
 'ulong': numpy.uint32,
 'L': numpy.uint32,
 8: numpy.uint32,
 'longlong': numpy.int64,
 'q': numpy.int64,
 'ulonglong': numpy.uint64,
 'Q': numpy.uint64,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.longdouble,
 'g': numpy.longdouble,
 13: numpy.longdouble,
 'cfloat': numpy.complex128,
 'F': numpy.complex

In [36]:
np.ndarray((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
a = np.array([1,2,3,4], dtype='i1')

In [20]:
a

array([1, 2, 3, 4], dtype=int8)

In [21]:
a.shape

(4,)

In [18]:
a.dtype

dtype('int32')

In [10]:
b = np.array([[1,2,3],[4,5,'6']])

In [11]:
b

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U11')

In [22]:
b.shape

(2, 3)

In [23]:
b.size

6

In [24]:
b.ndim

2

In [5]:
print(a)

[1 2 3 4]


In [4]:
type(a)

numpy.ndarray

In [31]:
aa = np.eye(3)

In [32]:
aa

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.tri(4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [48]:
a = {'a':1, 'b':[2,3,3,4,5],'c':'abcd'}

In [49]:
print(a)

{'a': 1, 'b': [2, 3, 3, 4, 5], 'c': 'abcd'}


In [50]:
pprint(a)

{'a': 1, 'b': [2, 3, 3, 4, 5], 'c': 'abcd'}


In [38]:
from pprint import pprint

In [40]:
pprint(b)

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U11')


In [41]:
print(b)

[['1' '2' '3']
 ['4' '5' '6']]


In [37]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [51]:
a = np.arange(48).reshape(3,4,4)

In [53]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [54]:
import tensorflow as tf

In [55]:
(X_train,y_train),(X_test,y_test) = tf.keras.datasets.mnist.load_data()

In [59]:
len(dir(X_train))

165

In [60]:
np.lookfor('sum')

Search results for 'sum'
------------------------
numpy.sum
    Sum of array elements over a given axis.
numpy.cumsum
    Return the cumulative sum of the elements along a given axis.
numpy.einsum
    einsum(subscripts, *operands, out=None, dtype=None, order='K',
numpy.nansum
    Return the sum of array elements over a given axis treating Not a
numpy.nancumsum
    Return the cumulative sum of array elements over a given axis treating Not a
numpy.einsum_path
    Evaluates the lowest cost contraction order for an einsum expression by
numpy.trace
    Return the sum along diagonals of the array.
numpy.ma.sum
    Return the sum of the array elements over the given axis.
numpy.bool8.sum
    Scalar method identical to the corresponding array attribute.
numpy.polyadd
    Find the sum of two polynomials.
numpy.ma.cumsum
    Return the cumulative sum of the array elements over the given axis.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.bool8.cumsum
    Scalar

In [61]:
np.info(np.einsum)

 einsum(*operands, out=None, optimize=False, **kwargs)

einsum(subscripts, *operands, out=None, dtype=None, order='K',
       casting='safe', optimize=False)

Evaluates the Einstein summation convention on the operands.

Using the Einstein summation convention, many common multi-dimensional,
linear algebraic array operations can be represented in a simple fashion.
In *implicit* mode `einsum` computes these values.

In *explicit* mode, `einsum` provides further flexibility to compute
other array operations that might not be considered classical Einstein
summation operations, by disabling, or forcing summation over specified
subscript labels.

See the notes and examples for clarification.

Parameters
----------
subscripts : str
    Specifies the subscripts for summation as comma separated list of
    subscript labels. An implicit (classical Einstein summation)
    calculation is performed unless the explicit indicator '->' is
    included as well as subscript labels of the precise output

In [62]:
a = np.array([1,2,3])
b = np.array([1,2,3])

In [63]:
np.dot(a,b)

14

In [64]:
a.dot(b)

14

In [65]:
a@b

14

In [66]:
aa = np.array([[1,2,3]])
bb = np.array([[1,2,3]])

In [67]:
aa@bb

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

In [69]:
aa = np.array([[1,2],[3,4]])
bb = np.array([[1,2],[3,5]])

In [70]:
aa@bb

array([[ 7, 12],
       [15, 26]])

In [74]:
aa

array([[1, 2],
       [3, 4]])

In [75]:
bb

array([[1, 2],
       [3, 5]])

In [71]:
aa+bb

array([[2, 4],
       [6, 9]])

In [72]:
aa*bb

array([[ 1,  4],
       [ 9, 20]])

In [73]:
aa-bb

array([[ 0,  0],
       [ 0, -1]])

In [76]:
aa

array([[1, 2],
       [3, 4]])

In [77]:
cc = np.array([[1,2,3],[4,5,6]])

In [78]:
aa

array([[1, 2],
       [3, 4]])

In [79]:
cc

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
aa + cc

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [81]:
aa + 1

array([[2, 3],
       [4, 5]])

In [82]:
cc - 2

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [84]:
np.ones_like(cc)

array([[1, 1, 1],
       [1, 1, 1]])

In [85]:
c = np.array([1,2,3])

In [86]:
cc + c

array([[2, 4, 6],
       [5, 7, 9]])

In [ ]:
[[1,2,3]
 [1,2,3]]

In [89]:
d = np.array([[1],[2]])

In [90]:
d.shape

(2, 1)

In [ ]:
[1, 1, 1]
[2, 2, 2]

In [91]:
cc + d

array([[2, 3, 4],
       [6, 7, 8]])

In [87]:
cc.shape

(2, 3)

In [88]:
c.shape

(3,)

In [92]:
x = np.array([[1,2]])
y = np.array([[1],[2]])

In [94]:
x

array([[1, 2]])

In [95]:
y

array([[1],
       [2]])

In [93]:
x + y

array([[2, 3],
       [3, 4]])

In [96]:
import seaborn as sns

In [97]:
tips = sns.load_dataset('tips')

In [100]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [102]:
tips[tips.sex=='Male']

total_bill   tip   sex smoker  day    time  size
1         10.34  1.66  Male     No  Sun  Dinner     3
2         21.01  3.50  Male     No  Sun  Dinner     3
3         23.68  3.31  Male     No  Sun  Dinner     2
5         25.29  4.71  Male     No  Sun  Dinner     4
6          8.77  2.00  Male     No  Sun  Dinner     2
..          ...   ...   ...    ...  ...     ...   ...
236       12.60  1.00  Male    Yes  Sat  Dinner     2
237       32.83  1.17  Male    Yes  Sat  Dinner     2
239       29.03  5.92  Male     No  Sat  Dinner     3
241       22.67  2.00  Male    Yes  Sat  Dinner     2
242       17.82  1.75  Male     No  Sat  Dinner     2

[157 rows x 7 columns]

In [103]:
np.add(3,4)

7

In [104]:
np.add([1,2],[3,4])

array([4, 6])

In [107]:
a = np.arange(24).reshape(4,6)

In [109]:
a[1][1]

7

In [110]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [139]:
a[0]

array([0, 1, 2, 3, 4, 5])

In [141]:
a[0,:]

array([0, 1, 2, 3, 4, 5])

In [142]:
a[0][:]

array([0, 1, 2, 3, 4, 5])

In [143]:
b = np.arange(24).reshape(2,3,4)

In [144]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [147]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [148]:
b[0][:][:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [149]:
b[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [150]:
b[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [152]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [153]:
b[0,1,2]

6

In [151]:
b[...,0]

array([[ 0,  4,  8],
       [12, 16, 20]])

In [154]:
b[...]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [130]:
a[a > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23])

In [111]:
a[1,1]

7

In [112]:
a[(0,1),(1,1)]

array([1, 7])

In [113]:
a[(2,2),(2,4)]

array([14, 16])

In [115]:
a[[2,2],[2,4]]

array([14, 16])

# 

In [116]:
a[[1,2]]

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [117]:
a[[2,1]]

array([[12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11]])

In [119]:
tips[['day','smoker']]

day smoker
0     Sun     No
1     Sun     No
2     Sun     No
3     Sun     No
4     Sun     No
..    ...    ...
239   Sat     No
240   Sat    Yes
241   Sat    Yes
242   Sat     No
243  Thur     No

[244 rows x 2 columns]

In [121]:
tips['day']

0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
       ... 
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: category
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [123]:
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder

In [126]:
le = LabelEncoder()
le.fit_transform(tips['day'])

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

In [128]:
oh = OrdinalEncoder()
oh.fit_transform(tips[['day']])

array([[2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [132]:
tips.smoker = 'No'

In [135]:
tips[tips.day == 'Sun']

total_bill   tip     sex smoker  day    time  size
0         16.99  1.01  Female     No  Sun  Dinner     2
1         10.34  1.66    Male     No  Sun  Dinner     3
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
186       20.90  3.50  Female     No  Sun  Dinner     3
187       30.46  2.00    Male     No  Sun  Dinner     5
188       18.15  3.50  Female     No  Sun  Dinner     3
189       23.10  4.00    Male     No  Sun  Dinner     3
190       15.69  1.50    Male     No  Sun  Dinner     2

[76 rows x 7 columns]

In [ ]:
# 23.07.06

In [ ]:
[1, 2, 3] < [1, 2, 4]
# False set은 sequence타입이 아니므로 대소비교불가
# [1, 2, 3] == [1, 2, 3] 의 같은지 비교는 가능

: 

In [ ]:
np.newaxis == None	# 커널트리를 제외하고 머신러닝에서 차원을 증가시킬일이없다. -> 차원의저주 -> overfitting

: 

In [ ]:
a[:.:.None]

In [ ]:
a[np.newaxis.:.:]

In [ ]:
a[None].shape

In [ ]:
a[:.None]

In [ ]:
a[:.None].shape

In [ ]:
a[0] = 100

In [ ]:
b

In [ ]:
a = [1, 2, 3, ]
c = a[:]
c[0] = 100
# a = [1, 2, 3] c = [100, 2, 3] -> a[:] a의 값을 복사

: 

In [ ]:
# 얕은 복사 va 깊은 복사
aa = [[1, 2], [3, 4]]
bb = aa[:]
bb[0][0] = 100
aa						# [[100, 2], [3, 4]


In [ ]:
a = np.arange(24)

: 

In [ ]:
a.reshape(3, 6)
# a.reshape(-5, 6) -> 4 * 6 = 24개

In [ ]:
x = np.arange(24).reshape(2, 3, 4)

: 

In [ ]:
# axis = 0 은 행마다 axis = 1은 열마다 axis = 2 는 
# https://jessicastringham.net/2017/12/31/stride-tricks/
# RGB컬러 이미지의 경우 axis = 0 -> x axis = 1 -> y axis = 2 -> z 로 압축하면 흑백이미지로 표현됨
x.sum(axis = 2)
x.max(axis = 2)

In [ ]:
# colum 끼리만 homo로 data type을 일치하면(colum끼리 homo genious) dataframe 

In [ ]:
from sklearn.ensemble import VotingClassifier, StackingClassifier

: 

In [ ]:
x = np.array(['rax', 9, 81, 0]), ['fido', 3, 27, 0], dtype=[('name', 'U10'), ('age', 'i4'), ('weiget', 'f4')]

In [ ]:
x['name']